### ISSUE TITLE
Decide who needs to be contacted to know that this project exists

### ISSUE THREAD

**Issue by richierocks** [RL10N/rl10n.github.io#2]
At least we need:
- Duncan Murdoch (murdoch _DOT_ duncan _AT_ gmail _DOT_ com)
- Brian Ripley (ripley _AT_ stats _DOT_ ox _DOT_ ac _DOT_ uk)
- [Maintainers of R translations](https://developer.r-project.org/TranslationTeams.html)
- The `translateR` team: Christopher Lucas (clucas _AT_ fas _DOT_ harvard _DOT_ edu) and Dustin Tingley (dtingley _AT_ gov _DOT_ harvard _DOT_ edu)

We could also scrape all CRAN packages with translations for the contact details of translators, but I don't know if this is too close to spamming.  Do you think this is OK?

Have I missed anyone?

**Comment by leeper** [comment]
I think that's everyone.

**Comment by richierocks** [comment]
Email sent.

**Comment by leeper** [comment]
Thanks!
