### ISSUE TITLE
Submit useR! abstract

### ISSUE THREAD

**Issue by richierocks** [RL10N/rl10n.github.io#3]
Form here: http://user2016.org/abstract-submission/index.html

Deadline is March 25.  We just need a title and a <250 word abstract.

**Comment by leeper** [comment]
Good idea! I cannot attend this year due to other commitments. Are you able to go?

**Comment by richierocks** [comment]
Ah, shame.  Yes, I'll be going along.  I've got another conference in Texas a couple of weeks before, so I'm planning to doing a road-trip to California.

**Comment by leeper** [comment]
Ooh, that should be awesome! Enjoy it!

**Comment by richierocks** [comment]
Any comments on abstract before I submit?  I figure that keeping it slightly vague is the safest approach, since we don't quite know where we'll be up to by June.

> RL10N: Let R Speak Your Language
> 
> RL10N is a project to make localising your R packages easier.  It includes tools for generating and maintaining the translation infrastructure in your packages, auto-generating error message translations with Google Translate and Microsoft Translator, and running translation projects with Amazon Mechanical Turk.

**Comment by leeper** [comment]
Looks good to me! Sorry again that I can't be there this year.

**Comment by richierocks** [comment]
Submitted.
